### ISSUE TITLE
A total of 0 anchor was found. Aborted.

### ISSUE THREAD

**Issue by ardy20** [chaimol/KK4D#4]
Hello Again
Why the analysis did not find any anchor? Could these be related to the header of my files? Please see below:

![cds header](https://user-images.githubusercontent.com/63028911/195807767-a466068e-027d-44ca-88b4-ead2766007be.JPG)
![gff3 header](https://user-images.githubusercontent.com/63028911/195807775-c13a7137-141e-4eb5-8ced-caa22874b988.JPG)
![protein header](https://user-images.githubusercontent.com/63028911/195807785-8b28fdf5-dab7-40aa-9ef9-eb4527303da5.JPG)

**Comment by chaimol** [comment]
Please provide the parameters when you run it. You should set `-key Name Name` , my example is `-key ID ID`.The `-key` is for set gff3 file the 9st column which character is same as the protein file and cds file sequence header.
